version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: telegram
      POSTGRES_DB: telegram
      POSTGRES_USER: telegram
